### ISSUE TITLE
Need Proportional Images

### ISSUE THREAD

**Issue by dylan-k** [WaltersArtMuseum/email-blueprints#2]
In keeping with our new plan to use and reuse a pair of "square and rectangle" images as often as possible, the rectangle images in this template need to be proportional to the images we create for CMS.

Currently those rectangles are sized at 560x400 and at 520x400

In order to be proportional to the master image (1200x630) the new rectangles would need to be 560x294 and 520x273 respectively

Squares are inherently proportional, so no change is needed to those.

**Comment by kateblanch** [comment]
I haven't been following this too closelfy - but I just wanted to suggest the ResourceSpace has a full set of tools to create images at any dimension you may choose, in batches. I can help set this up if you need these tools to resize images!

**Comment by dylan-k** [comment]
That's an exciting possibility, as it could enable us to create images, at our standard sizes, for anything in the collection, right?

For now, we're still in the very early days of having standard sizes though, so I would want to wait to implement anything on Resource Space, until we're sure we've got the sizes we can commit to.

We'd also want to consider what's possible with regard to cropping, detailing, scaling and skewing of the images. Often, in marketing and communications, we'd like to use a similar detail or crop, across various platforms, print, online, in-house etc. .

**Comment by kateblanch** [comment]
Yes, images of anything in the collection for which there's an image - always the caveat :) - can be made into a derivative of any size. For batch processing (many different images) we'd set us a derivative "type" for you to your specs. For one-off processing (one particular image) there is a "transform" feature where you can crop, scale, zoom in, change format, etc. It's pretty awesome!

**Comment by dylan-k** [comment]
That sounds like a real lifesaver. I can't wait to try it out. :)

**Comment by kateblanch** [comment]
Yahoo! Just click on “transform” when youre on an image detail page! It’s located under the download-size options.
http://resourcespace.thewalters.org/plugins/transform/pages/crop.php?ref=213248


Kate Blanch
Administrator, Museum Databases
410.547.9000 x.266 | kblanch@thewalters.org

The Walters Art Museum
600 North Charles Street, Baltimore, MD 21201-5185
thewalters.org<http://thewalters.org/>
