### ISSUE TITLE
Logo Header More Like Teacher Template

### ISSUE THREAD

**Issue by dylan-k** [WaltersArtMuseum/email-blueprints#6]
We'd like to adjust the logo header:
- [ ] make it look like what was designed for the teacher template (see screenshot below)
- [ ] make it responsive
- [ ] add functionality so that content author/editor can use mailchimp to swap out different logo/headers

![dconkpdlxaoweenxu6lpa1nl2rhv46kydggil-ckzr8](https://cloud.githubusercontent.com/assets/2204716/7302942/021e130a-e9bb-11e4-9c69-9f1a6a1b614e.png)

**Comment by TheaCanlas** [comment]
Emailing Tony about this
